### ISSUE TITLE
Add a sign-up button for volunteers

### ISSUE THREAD

**Issue by michaltrzesimiech** [Stay-Home-Campaign/stay-home-campaign.github.io#12]
I.e. linked to a google spreadsheet. @michaltrzesimiech needs to look into admin aspect of this.

**Comment by michaltrzesimiech** [comment]
The form is ready https://docs.google.com/forms/d/e/1FAIpQLSdyQnwVWWw6cTNkoaxXdB-XTEbtD45lpFD4QPKfBHyytyAlZw/viewform

**Comment by siddv** [comment]
This is done. However, all locales of the site have an english CTA for now. Need translations for the link, then we can add them in: https://docs.google.com/spreadsheets/d/1IYTdY55u1Wk6VRWfggxbtmTaNOYCF-8MsNf5sfeL8fM/edit#gid=0

**Comment by siddv** [comment]
Closing as only English was a requirement
